# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Patient',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'patients'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='category',
            new_name='patient',
        ),
    ]
