# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_record_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
    ]
